### ISSUE TITLE
Error when installing qiimer package for R

### ISSUE THREAD

**Issue by ZhangTechnion** [kylebittinger/qiimer#11]
Hi,
I tried to install ‘qiimer’ package for R (3.6.2) from CRAN under Win10, but I failed. Then I tried to install it locally from ‘qiimer_0.9.4.tar.gz’, and failed, neither.

I do not understand why CRAN does not afford this package anymore. I wonder how can I install it on my PC? Because I need it for another package ‘Tax4Fun’.

The following are the command I tried,

(1) Installation from CRAN.

> install.packages("qiimer")
Installing package into ‘C:/Users/User/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘qiimer’ is not available (for R version 3.6.2)

(2) Installation locally.

> install.packages("C:/Users/User/Downloads/qiimer_0.9.4.tar.gz", repos = NULL, type = "source")
Installing package into ‘C:/Users/User/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
ERROR: dependency 'pheatmap' is not available for package 'qiimer'
  removing 'C:/Users/User/Documents/R/win-library/3.6/qiimer'
Warning in install.packages :
  installation of package ‘C:/Users/User/Downloads/qiimer_0.9.4.tar.gz’ had non-zero exit status

Thank you very much!
Zhang

**Comment by kylebittinger** [comment]
Zhang,

Please try installing pheatmap, check that pheatmap is installed properly, then try it again with the local installation of qiimer. Please let me know by email how it works out, either way.

**Comment by ZhangTechnion** [comment]
Hi Kyle,

Thank you for your reply. After updating the Package 'phreatmap', I have succeed with the local installation. As for the installation from CRAN, it has no effect.
