### ISSUE TITLE
dist_groups column for within or between distance

### ISSUE THREAD

**Issue by cchehoud** [kylebittinger/qiimer#5]
Add a column called "IsWithin" which specifies if the distance is within a group or between a group.

Longer:
Currently, your dist_groups function has a column called Label which starts with "Within" or "Between". For factors with many levels (such as Subject ID), it is difficult to visualize the within distance for every subject ID. Adding a "IsWithin" column will allow users to quickly plot "Within" and "Between" (not within) distances.

**Comment by kylebittinger** [comment]
Moving the distance functions to the usedist package, so returning to the distance-related issues here.

To solve this, I use Group1 == Group2 as an indicator for within-group vs. between-group distances.
